# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers
        environment:
          AWS_REGION: eu-west-1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies --no-daemon

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run unit tests
      - run:
          command: gradle ci_unit --no-daemon
          name: ci_unit
          environment:
            SERVER_URL: https://alpha.tramchester.com
            ENV: Dev
            PLACE: Dev
      - run:
          command: gradle integration --no-daemon
          name: integration
      - run:
          command: gradle upload --no-daemon
          name: upload
      - run:
          name: deployDev
          command: gradle deploy updateLB tidy --no-daemon
          environment:
            ENV: Dev
      - run:
          name: setupLocale
          command: |
            sudo sh -c 'echo en_GB.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen en_GB.UTF-8
            sudo update-locale en_GB.UTF-8
      - run:
          name: acceptance
          command: |
            export LANG="en_GB.UTF-8"
            gradle appium --no-daemon
          environment:
            SERVER_URL: https://alpha.tramchester.com
      - run:
          name: deployUAT
          environment:
            ENV: UAT
          command: ./gradlew deploy updateLB tidy --no-daemon
      - run: mkdir -p workspace
      - run: echo "export RELEASE_NUMBER=$CIRCLE_BUILD_NUM" > workspace/release_num.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - release_num.txt
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  deployProd:
    docker:
    # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: gradle dependencies --no-daemon
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: deployProd
          environment:
            ENV: ProdBlue
            AWS_REGION: eu-west-1
          command: |
            source workspace/release_num.txt
            echo release number is $RELEASE_NUMBER
            ./gradlew deploy --no-daemon
            ./gradlew updateLB --no-daemon
workflows:
  version: 2
  buildStep:
    jobs:
    - build
    - hold:
        type: approval
        requires:
        - build
    - deployProd:
        requires:
        - hold