# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0.6-jdk-buster-node-browsers
        environment:
          AWS_REGION: eu-west-1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JAVA_TOOL_OPTIONS: -Xmx3g
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}

      - run: gradle dependencies --no-daemon
      # run unit tests
      - run:
          name: unit
          command: gradle unit --no-daemon
      - run:
          name: integration
          command: gradle integration --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-deps-{{ checksum "build.gradle" }}
      - run:
          name: upload
          command: gradle upload --no-daemon
      - save_cache:
          paths:
            - ./node_modules
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: deployDev
          command: gradle deploy updateLB tidy --no-daemon
          environment:
            ENV: Dev
      - run:
          name: setupLocale
          command: |
            sudo sh -c 'echo en_GB.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen en_GB.UTF-8
            sudo update-locale en_GB.UTF-8
      - run:
          name: acceptance
          command: |
            export LANG="en_GB.UTF-8"
            gradle appium --no-daemon
          environment:
            SERVER_URL: https://alpha.tramchester.com
      - run:
          name: deployUAT
          environment:
            ENV: UAT
          command: gradle deploy updateLB tidy --no-daemon
      - run: mkdir -p workspace
      - run: echo "export RELEASE_NUMBER=$CIRCLE_BUILD_NUM" > workspace/release_num.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - release_num.txt
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  deployProd:
    docker:
    # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
          - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run: gradle dependencies --no-daemon
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: deployProd
          environment:
            ENV: ProdBlue
            AWS_REGION: eu-west-1
          command: |
            source workspace/release_num.txt
            echo release number is $RELEASE_NUMBER
            gradle deploy --no-daemon
            gradle updateLB --no-daemon
workflows:
  version: 2
  buildStep:
    jobs:
    - build
    - hold:
        type: approval
        requires:
        - build
    - deployProd:
        requires:
        - hold