server:
  applicationContextPath: /
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 8KiB
    minimumEntitySize: 160B

rebuildGraph: true
secureHost: tramchester.com
graphName: buses.db
closedStations: []
dataSources:
  -
    name: tfgm
    URL: ${TRAM_DATAURL:- http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip}
    checkURL: http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip
    dataPath: data/bus
    unzipPath: gtdf-out
    hasFeedInfo: true
    transportModes: [ bus ]
instanceDataUrl: http://169.254.169.254
liveDataUrl: https://api.tfgm.com/odata/Metrolinks
liveDataSubscriptionKey: ${TFGMAPIKEY:- ""}
liveDataS3Bucket: tramchesterlivedata
liveDataRefreshPeriodSeconds: 20
loadPostcodes: true
createNeighbours: true
distanceToNeighboursKM: 0.25
postcodeDataPath: data/codepo_gb/Data/CSV
postcodeZip: data/codepo_gb.zip
removeRouteNameSuffix: true
maxWait: 25
numberQueries: 3
queryInterval: 12
maxNumberResults: 5
maxJourneyDuration: 170
nearestStopRangeKM: 1.6
numOfNearestStops: 5
numOfNearestStopsForWalking: 3
walkingMPH: 3.0
recentStopsToShow: 5
dataExpiryThreadhold: 3
maxNumberMissingLiveMessages: 10

changeAtInterchangeOnly: false

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: logs/tramchester_buses.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_buses-%d.log
      archivedFileCount: 5
      timeZone: UTC

# TODO only for dev environments
assets:
  overrides:
    # Override requests to /app/${1} to instead look in
    # ${working directory}/src/main/app/${1}
    /app: src/main/resources/app/