server:
  applicationContextPath: /
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 8KiB
    minimumEntitySize: 160B

secureHost: tramchester.com
staticAssetCacheTimeSeconds: 300
graphName: tramchester.db
neo4jPagecacheMemory: 100m
stationClosures: []
instanceDataUrl: http://169.254.169.254
dataSources:
  -
    name: tfgm
    URL: ${TRAM_DATAURL:- http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip}
    checkURL: http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip
    dataPath: data/tram
    unzipPath: gtdf-out
    hasFeedInfo: true
    transportModes: [ tram ]
    transportModesWithPlatforms: [ Tram ]
    noServices: [ 2020-12-25 ]
bounds:
  minEastings: 333211
  minNorthings: 373264
  maxEasting: 414492
  maxNorthings: 437779
liveData:
  dataUrl: https://api.tfgm.com/odata/Metrolinks
  dataSubscriptionKey: ${TFGMAPIKEY:- ""}
  s3Bucket: tramchesterlivedata
  s3Prefix: ${PLACE:- "test"}
  refreshPeriodSeconds: 20
  maxNumberStationsWithoutMessages: 10
  maxNumberStationsWithoutData: 5
loadPostcodes: false
createNeighbours: false
distanceToNeighboursKM: 0.4
postcodeDataPath: data/codepo_gb/Data/CSV
postcodeZip: data/codepo_gb.zip
removeRouteNameSuffix: true
maxWait: 25
numberQueries: 3
queryInterval: 12
maxNumberResults: 5
maxJourneyDuration: 122
nearestStopRangeKM: 1.6
nearestStopForWalkingRangeKM: 1.6
numOfNearestStopsToOffer: 5
numOfNearestStopsForWalking: 3
walkingMPH: 3.0
recentStopsToShow: 5
dataExpiryThreadhold: 3
changeAtInterchangeOnly: true

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: logs/tramchester_local.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_local-%d.log
      archivedFileCount: 5
      timeZone: UTC
