server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

redirectHTTP: ${REDIRECTHTTP:- false}
secureHost: tramchester.com

rebuildGraph: true
unzipPath: gtdf-out
graphName: databases/tramchesterAcceptance.db
closedStations: []
agencies:
  - MET
instanceDataUrl: http://169.254.169.254
tramDataUrl: ${TRAM_DATAURL:- http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip}
tramDataCheckUrl: http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip
liveDataUrl: https://api.tfgm.com/odata/Metrolinks
liveDataSubscriptionKey: ${TFGMAPIKEY:- ""}
liveDataS3Bucket: tramchesterlivedata
liveDataRefreshPeriodSeconds: 20
dataPath: data/tram
postcodeDataPath: data/codepo_gb/Data/CSV
postcodeZip: data/codepo_gb.zip
removeRouteNameSuffix: true
maxWait: 25
maxNumberResults: 5
maxJourneyDuration:  112
numberQueries: 3
queryInterval: 12
nearestStopRangeKM: 2
numOfNearestStops:  5
numOfNearestStopsForWalking:  3
walkingMPH: 3
recentStopsToShow: 5
dataExpiryThreadhold: 3
maxNumberMissingLiveMessages: 5
changeAtInterchangeOnly: true

createLocality: false

swagger:
  resourcePackage: com.tramchester.resources

logging:
  level: INFO
  loggers:
    root: INFO
    com.tramchester: INFO
    org.eclipse.jetty.servlet: INFO
    io.dropwizard.jersey.jackson: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: build/reports/tests/accept_tramchester.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: build/reports/tests/accept_tramchester-%d.log
      archivedFileCount: 5
      timeZone: UTC
