server:
  applicationContextPath: /
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 8KiB
    minimumEntitySize: 160B

secureHost: tramchester.com

rebuildGraph: true
graphName: trains.db
unzipPath: gtdf-out
closedStations: []
transportModes: [ train ]
instanceDataUrl: http://169.254.169.254
tramDataUrl: ${TRAM_DATAURL:- http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip}
tramDataCheckUrl: http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip
liveDataUrl: https://api.tfgm.com/odata/Metrolinks
liveDataSubscriptionKey: ${TFGMAPIKEY:- ""}
liveDataS3Bucket: tramchesterlivedata
liveDataRefreshPeriodSeconds: 20
dataPath: data/tram
loadPostcodes: false
createNeighbours: false
distanceToNeighboursKM: 0.25
postcodeDataPath: data/codepo_gb/Data/CSV
postcodeZip: data/codepo_gb.zip
removeRouteNameSuffix: true
maxWait: 25
numberQueries: 5
queryInterval: 10
maxNumberResults: 5
maxJourneyDuration: 112
nearestStopRangeKM: 1.6
numOfNearestStops: 5
numOfNearestStopsForWalking: 3
walkingMPH: 3.0
recentStopsToShow: 5
dataExpiryThreadhold: 3
maxNumberMissingLiveMessages: 10

changeAtInterchangeOnly: false

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: INFO
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: logs/tramchester_trains.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_trains-%d.log
      archivedFileCount: 5
      timeZone: UTC

# TODO only for dev environments
assets:
  overrides:
    # Override requests to /app/${1} to instead look in
    # ${working directory}/src/main/app/${1}
    /app: src/main/resources/app/